package bach

type Comp struct {
	BWV, Title string
}

// All Cantatas by Bach
// Source: Wikipedia
var AllCantatas [][]Comp = [][]Comp{
	[]Comp{
		Comp{"1", "Wie schön leuchtet der Morgenstern"},
		Comp{"2", "Ach Gott, vom Himmel sieh darein"},
		Comp{"3", "Ach Gott, wie manches Herzeleid"},
		Comp{"4", "Christ lag in Todes Banden"},
		Comp{"5", "Wo soll ich fliehen hin"},
		Comp{"6", "Bleib bei uns, denn es will Abend werden"},
		Comp{"7", "Christ unser Herr zum Jordan kam"},
		Comp{"8", "Liebster Gott, wenn werd ich sterben?"},
		Comp{"9", "Es ist das Heil uns kommen her"},
		Comp{"10", "Meine Seel erhebt den Herren"},
		Comp{"11", "Lobet Gott in seinen Reichen"},
		Comp{"12", "Weinen, Klagen, Sorgen, Zagen"},
		Comp{"13", "Meine Seufzer, meine Tränen"},
		Comp{"14", "Wär Gott nicht mit uns diese Zeit"},
		Comp{"15", "Denn du wirst meine Seele nicht in der Hölle lassen"},
		Comp{"16", "Herr Gott, dich loben wir"},
		Comp{"17", "Wer Dank opfert, der preiset mich"},
		Comp{"18", "Gleichwie der Regen und Schnee vom Himmel fällt"},
		Comp{"19", "Es erhub sich ein Streit"},
		Comp{"20", "O Ewigkeit, du Donnerwort"},
		Comp{"21", "Ich hatte viel Bekümmernis"},
		Comp{"22", "Jesus nahm zu sich die Zwölfe"},
		Comp{"23", "Du wahrer Gott und Davids Sohn"},
		Comp{"24", "Ein ungefärbt Gemüte"},
		Comp{"25", "Es ist nichts Gesundes an meinem Leibe"},
		Comp{"26", "Ach wie flüchtig, ach wie nichtig"},
		Comp{"27", "Wer weiß, wie nahe mir mein Ende?"},
		Comp{"28", "Gottlob! nun geht das Jahr zu Ende"},
		Comp{"29", "Wir danken dir, Gott, wir danken dir"},
		Comp{"30", "Freue dich, erlöste Schar"},
		Comp{"30a", "Angenehmes Wiederau"},
		Comp{"31", "Der Himmel lacht! Die Erde jubilieret"},
		Comp{"32", "Liebster Jesu, mein Verlangen"},
		Comp{"33", "Allein zu dir, Herr Jesu Christ"},
		Comp{"34", "O ewiges Feuer, o Ursprung der Liebe"},
		Comp{"34a", "O ewiges Feuer, o Ursprung der Liebe"},
		Comp{"35", "Geist und Seele wird verwirret"},
		Comp{"36", "Schwingt freudig euch empor"},
		Comp{"36a", "Steigt freudig in die Luft"},
		Comp{"36b", "Die Freude reget sich"},
		Comp{"36c", "Schwingt freudig euch empor"},
		Comp{"37", "Wer da gläubet und getauft wird"},
		Comp{"38", "Aus tiefer Not schrei ich zu dir"},
		Comp{"39", "Brich dem Hungrigen dein Brot"},
		Comp{"40", "Darzu ist erschienen der Sohn Gottes"},
		Comp{"41", "Jesu, nun sei gepreiset"},
		Comp{"42", "Am Abend aber desselbigen Sabbats"},
		Comp{"43", "Gott fähret auf mit Jauchzen"},
		Comp{"44", "Sie werden euch in den Bann tun"},
		Comp{"45", "Es ist dir gesagt, Mensch, was gut ist"},
		Comp{"46", "Schauet doch und sehet, ob irgend ein Schmerz sei"},
		Comp{"47", "Wer sich selbst erhöhet, der soll erniedriget werden"},
		Comp{"48", "Ich elender Mensch, wer wird mich erlösen"},
		Comp{"49", "Ich geh und suche mit Verlangen"},
		Comp{"50", "Nun ist das Heil und die Kraft"},
		Comp{"51", "Jauchzet Gott in allen Landen"},
		Comp{"52", "Falsche Welt, dir trau ich nicht"},
		Comp{"53", "Schlage doch, gewünschte Stunde"},
		Comp{"54", "Widerstehe doch der Sünde"},
		Comp{"55", "Ich armer Mensch, ich Sündenknecht"},
		Comp{"56", "Ich will den Kreuzstab gerne tragen"},
		Comp{"57", "Selig ist der Mann"},
		Comp{"58", "Ach Gott, wie manches Herzeleid"},
		Comp{"59", "Wer mich liebet, der wird mein Wort halten"},
		Comp{"60", "O Ewigkeit, du Donnerwort"},
		Comp{"61", "Nun komm, der Heiden Heiland"},
		Comp{"62", "Nun komm, der Heiden Heiland"},
		Comp{"63", "Christen, ätzet diesen Tag"},
		Comp{"64", "Sehet, welch eine Liebe hat uns der Vater erzeiget"},
		Comp{"65", "Sie werden aus Saba alle kommen"},
		Comp{"66", "Erfreut euch, ihr Herzen"},
		Comp{"66a", "Der Himmel dacht auf Anhalts Ruhm und Glück"},
		Comp{"67", "Halt im Gedächtnis Jesum Christ"},
		Comp{"68", "Also hat Gott die Welt geliebt"},
		Comp{"69", "Lobe den Herrn, meine Seele"},
		Comp{"69a", "Lobe den Herrn, meine Seele"},
		Comp{"70", "Wachet! betet! betet! wachet!"},
		Comp{"70a", "Wachet! betet! betet! wachet!"},
		Comp{"71", "Gott ist mein König"},
		Comp{"72", "Alles nur nach Gottes Willen"},
		Comp{"73", "Herr, wie du willt, so schicks mit mir"},
		Comp{"74", "Wer mich liebet, der wird mein Wort halten"},
		Comp{"75", "Die Elenden sollen essen"},
		Comp{"76", "Die Himmel erzählen die Ehre Gottes"},
		Comp{"77", "Du sollt Gott, deinen Herren, lieben"},
		Comp{"78", "Jesu, der du meine Seele"},
		Comp{"79", "Gott der Herr ist Sonn und Schild"},
		Comp{"80", "Ein feste Burg ist unser Gott"},
		Comp{"80a", "Alles, was von Gott geboren"},
		Comp{"80b", "Ein feste Burg ist unser Gott"},
		Comp{"81", "Jesus schläft, was soll ich hoffen?"},
		Comp{"82", "Ich habe genug"},
		Comp{"83", "Erfreute Zeit im neuen Bunde"},
		Comp{"84", "Ich bin vergnügt mit meinem Glücke"},
		Comp{"85", "Ich bin ein guter Hirt"},
		Comp{"86", "Wahrlich, wahrlich, ich sage euch"},
		Comp{"87", "Bisher habt ihr nichts gebeten in meinem Namen"},
		Comp{"88", "Siehe, ich will viel Fischer aussenden"},
		Comp{"89", "Was soll ich aus dir machen, Ephraim"},
		Comp{"90", "Es reißet euch ein schrecklich Ende"},
		Comp{"91", "Gelobet seist du, Jesu Christ"},
		Comp{"92", "Ich hab in Gottes Herz und Sinn"},
		Comp{"93", "Wer nur den lieben Gott läßt walten"},
		Comp{"94", "Was frag ich nach der Welt"},
		Comp{"95", "Christus, der ist mein Leben"},
		Comp{"96", "Herr Christ, der einge Gottessohn"},
		Comp{"97", "In allen meinen Taten"},
		Comp{"98", "Was Gott tut, das ist wohlgetan"},
		Comp{"99", "Was Gott tut, das ist wohlgetan"},
		Comp{"100", "Was Gott tut, das ist wohlgetan"},
		Comp{"101", "Nimm von uns, Herr, du treuer Gott"},
		Comp{"102", "Herr, deine Augen sehen nach dem Glauben"},
		Comp{"103", "Ihr werdet weinen und heulen"},
		Comp{"104", "Du Hirte Israel, höre"},
		Comp{"105", "Herr, gehe nicht ins Gericht mit deinem Knecht"},
		Comp{"106", "Gottes Zeit ist die allerbeste Zeit"},
		Comp{"107", "Was willst du dich betrüben"},
		Comp{"108", "Es ist euch gut, daß ich hingehe"},
		Comp{"109", "Ich glaube, lieber Herr, hilf meinem Unglauben"},
		Comp{"110", "Unser Mund sei voll Lachens"},
		Comp{"111", "Was mein Gott will, das g'scheh allzeit"},
		Comp{"112", "Der Herr ist mein getreuer Hirt"},
		Comp{"113", "Herr Jesu Christ, du höchstes Gut"},
		Comp{"114", "Ach, lieben Christen, seid getrost"},
		Comp{"115", "Mache dich, mein Geist, bereit"},
		Comp{"116", "Du Friedefürst, Herr Jesu Christ"},
		Comp{"117", "Sei Lob und Ehr dem höchsten Gut"},
		Comp{"118", "O Jesu Christ, meins Lebens Licht"},
		Comp{"119", "Preise, Jerusalem, den Herrn"},
		Comp{"120", "Gott, man lobet dich in der Stille"},
		Comp{"120a", "Herr Gott, Beherrscher aller Dinge"},
		Comp{"120b", "Gott, man lobet dich in der Stille"},
		Comp{"121", "Christum wir sollen loben schon"},
		Comp{"122", "Das neugeborne Kindelein"},
		Comp{"123", "Liebster Immanuel, Herzog der Frommen"},
		Comp{"124", "Meinen Jesum laß ich nicht"},
		Comp{"125", "Mit Fried und Freud ich fahr dahin"},
		Comp{"126", "Erhalt uns, Herr, bei deinem Wort"},
		Comp{"127", "Herr Jesu Christ, wahr' Mensch und Gott"},
		Comp{"128", "Auf Christi Himmelfahrt allein"},
		Comp{"129", "Gelobet sei der Herr, mein Gott"},
		Comp{"130", "Herr Gott, dich loben alle wir"},
		Comp{"131", "Aus der Tiefen rufe ich, Herr, zu dir"},
		Comp{"132", "Bereitet die Wege, bereitet die Bahn"},
		Comp{"133", "Ich freue mich in dir"},
		Comp{"134", "Ein Herz, das seinen Jesum lebend weiß"},
		Comp{"134a", "Die Zeit, die Tag und Jahre macht"},
		Comp{"135", "Ach Herr, mich armen Sünder"},
		Comp{"136", "Erforsche mich, Gott, und erfahre mein Herz"},
		Comp{"137", "Lobe den Herren, den mächtigen König der Ehren"},
		Comp{"138", "Warum betrübst du dich, mein Herz"},
		Comp{"139", "Wohl dem, der sich auf seinen Gott"},
		Comp{"140", "Wachet auf, ruft uns die Stimme"},
		Comp{"141", "Das ist je gewißlich wahr"},
		Comp{"142", "Uns ist ein Kind geboren"},
		Comp{"143", "Lobe den Herrn, meine Seele"},
		Comp{"144", "Nimm, was dein ist, und gehe hin"},
		Comp{"145", "Ich lebe, mein Herze, zu deinem Ergötzen"},
		Comp{"146", "Wir müssen durch viel Trübsal"},
		Comp{"147", "Herz und Mund und Tat und Leben"},
		Comp{"147a", "Herz und Mund und Tat und Leben"},
		Comp{"148", "Bringet dem Herrn Ehre seines Namens"},
		Comp{"149", "Man singet mit Freuden vom Sieg"},
		Comp{"150", "Nach dir, Herr, verlanget mich"},
		Comp{"151", "Süßer Trost, mein Jesus kömmt"},
		Comp{"152", "Tritt auf die Glaubensbahn"},
		Comp{"153", "Schau, lieber Gott, wie meine Feind"},
		Comp{"154", "Mein liebster Jesus ist verloren"},
		Comp{"155", "Mein Gott, wie lang, ach lange?"},
		Comp{"156", "Ich steh mit einem Fuß im Grabe"},
		Comp{"157", "Ich lasse dich nicht, du segnest mich denn"},
		Comp{"158", "Der Friede sei mit dir"},
		Comp{"159", "Sehet, wir gehn hinauf gen Jerusalem"},
		Comp{"160", "Ich weiß, daß mein Erlöser lebt"},
		Comp{"161", "Komm, du süße Todesstunde"},
		Comp{"162", "Ach! ich sehe, itzt, da ich zur Hochzeit gehe"},
		Comp{"163", "Nur jedem das Seine"},
		Comp{"164", "Ihr, die ihr euch von Christo nennet"},
		Comp{"165", "O heilges Geist- und Wasserbad"},
		Comp{"166", "Wo gehest du hin?"},
		Comp{"167", "Ihr Menschen, rühmet Gottes Liebe"},
		Comp{"168", "Tue Rechnung! Donnerwort"},
		Comp{"169", "Gott soll allein mein Herze haben"},
		Comp{"170", "Vergnügte Ruh, beliebte Seelenlust"},
		Comp{"171", "Gott, wie dein Name, so ist auch dein Ruhm"},
		Comp{"172", "Erschallet, ihr Lieder, erklinget, ihr Saiten!"},
		Comp{"173", "Erhöhtes Fleisch und Blut"},
		Comp{"173a", "Durchlauchtster Leopold"},
		Comp{"174", "Ich liebe den Höchsten von ganzem Gemüte"},
		Comp{"175", "Er rufet seinen Schafen mit Namen"},
		Comp{"176", "Es ist ein trotzig und verzagt Ding"},
		Comp{"177", "Ich ruf zu dir, Herr Jesu Christ"},
		Comp{"178", "Wo Gott der Herr nicht bei uns hält"},
		Comp{"179", "Siehe zu, daß deine Gottesfurcht nicht Heuchelei sei"},
		Comp{"180", "Schmücke dich, o liebe Seele"},
		Comp{"181", "Leichtgesinnte Flattergeister"},
		Comp{"182", "Himmelskönig, sei willkommen"},
		Comp{"183", "Sie werden euch in den Bann tun"},
		Comp{"184", "Erwünschtes Freudenlicht"},
		Comp{"185", "Barmherziges Herze der ewigen Liebe"},
		Comp{"186", "Ärgre dich, o Seele, nicht"},
		Comp{"186a", "Ärgre dich, o Seele, nicht"},
		Comp{"187", "Es wartet alles auf dich"},
		Comp{"188", "Ich habe meine Zuversicht"},
		Comp{"189", "Meine Seele rühmt und preist"},
		Comp{"190", "Singet dem Herrn ein neues Lied"},
		Comp{"190a", "Singet dem Herrn ein neues Lied"},
		Comp{"191", "Gloria in excelsis Deo"},
		Comp{"192", "Nun danket alle Gott"},
		Comp{"193", "Ihr Tore zu Zion"},
		Comp{"193a", "Ihr Häuser des Himmels, ihr scheinenden Lichter"},
		Comp{"194", "Höchsterwünschtes Freudenfest"},
		Comp{"195", "Dem Gerechten muß das Licht"},
		Comp{"196", "Der Herr denket an uns"},
		Comp{"197", "Gott ist unsre Zuversicht"},
		Comp{"197a", "Ehre sei Gott in der Höhe"},
		Comp{"198", "Laß, Fürstin, laß noch einen Strahl"},
		Comp{"199", "Mein Herze schwimmt im Blut"},
		Comp{"200", "Bekennen will ich seinen Namen"},
		Comp{"201", "Geschwinde, ihr wirbelnden Winde"},
		Comp{"202", "Weichet nur, betrübte Schatten"},
		Comp{"203", "Amore traditore"},
		Comp{"204", "Ich bin in mir vergnügt"},
		Comp{"205", "Zerreißet, zersprenget, zertrümmert die Gruft"},
		Comp{"205a", "Blast Lärmen, ihr Feinde"},
		Comp{"206", "Schleicht, spielende Wellen"},
		Comp{"207", "Vereinigte Zwietracht der wechselnden Saiten"},
		Comp{"207a", "Auf, schmetternde Töne der muntern Trompeten"},
		Comp{"208", "Was mir behagt, ist nur die muntre Jagd"},
		Comp{"208a", "Was mir behagt, ist nur die muntre Jagd"},
		Comp{"209", "Non sa che sia dolore"},
		Comp{"210", "O holder Tag, erwünschte Zeit"},
		Comp{"210a", "O angenehme Melodei"},
		Comp{"211", "Schweigt stille, plaudert nicht"},
		Comp{"212", "Mer hahn en neue Oberkeet"},
		Comp{"213", "Laßt uns sorgen, laßt uns wachen"},
		Comp{"214", "Tönet, ihr Pauken! Erschallet, Trompeten!"},
		Comp{"215", "Preise dein Glücke, gesegnetes Sachsen"},
		Comp{"216", "Vergnügte Pleißenstadt"},
		Comp{"216a", "Erwählte Pleißenstadt"},
		Comp{"217", "Gedenke, Herr, wie es uns gehet"},
		Comp{"218", "Gott der Hoffnung erfülle euch"},
		Comp{"219", "Siehe, es hat überwunden der Löwe"},
		Comp{"220", "Lobt ihn mit Herz und Munde"},
		Comp{"221", "Wer sucht die Pracht, wer wünscht den Glanz"},
		Comp{"222", "Mein Odem ist schwach"},
		Comp{"223", "Meine Seele soll Gott loben"},
		Comp{"224", "Reißt euch los, bedrängte Sinnen"},
		Comp{"244a", "Klagt, Kinder, klagt es aller Welt"},
		Comp{"249a", "Entfliehet, verschwindet, entweichet, ihr Sorgen"},
		Comp{"249b", "Verjaget, zerstreuet, zerrüttet, ihr Sterne"},
		Comp{"1045", "Violin Concerto movement"},
		Comp{"1083", "Tilge, Höchster, meine Sünden"},
		Comp{"1127", "Alles mit Gott und nichts ohn' ihn"},
		Comp{"Anh. 1", "Gesegnet ist die Zuversicht"},
		Comp{"Anh. 2", "Cantata for Trinity XIX"},
		Comp{"Anh. 3", "Gott, gib dein Gerichte dem Könige"},
		Comp{"Anh. 4", "Wünschet Jerusalem Glück"},
		Comp{"Anh. 4a", "Wünschet Jerusalem Glück"},
		Comp{"Anh. 5", "Lobet den Herrn, alle seine Heerscharen"},
		Comp{"Anh. 6", "Dich loben die lieblichen Strahlen der Sonne"},
		Comp{"Anh. 7", "Heut ist gewiß ein guter Tag"},
		Comp{"Anh. 8", "Neujahrskantate"},
		Comp{"Anh. 9", "Entfernet euch, ihr heitern Sterne"},
		Comp{"Anh. 10", "So kämpfet nur, ihr muntern Töne"},
		Comp{"Anh. 11", "Es lebe der König, der Vater im Lande"},
		Comp{"Anh. 12", "Frohes Volk, vernügte Sachsen"},
		Comp{"Anh. 13", "Willkommen! Ihr herrschenden Götter der Erden"},
		Comp{"Anh. 14", "Sein Segen fließt daher wie ein Strom"},
		Comp{"Anh. 15", "Siehe der Hüter Israel"},
		Comp{"Anh. 16", "Schließt die Gruft! ihr Trauerglocken"},
		Comp{"Anh. 17", "Mein Gott, nimm die gerechte Seele"},
		Comp{"Anh. 18", "Froher Tag, verlangte Stunden"},
		Comp{"Anh. 19", "Thomana saß annoch betrübt"},
		Comp{"Anh. 20", "Lateinische Ode"},
		Comp{"Anh. 21", "Meine Seel erhebt den Herren"},
		Comp{"Anh. 190", "Ich bin ein Pilgrim auf der Welt"},
		Comp{"Anh. 191", "Leb ich oder leb ich nicht"},
		Comp{"Anh. 192", "BWV Anh. 192|Ratswahlkantate Mühlhausen 1709"},
		Comp{"Anh. 193", "Herrscher des Himmels, König der Ehren"},
		Comp{"Anh. 194", "Cantata for the birthday of Johann August of Anhalt-Zerbst"},
		Comp{"Anh. 195", "Murmelt nur, ihr heitern Bäche"},
		Comp{"Anh. 196", "Auf, süß entzückende Gewalt"},
		Comp{"Anh. 197", "Ihr wallenden Wolken"},
		Comp{"Anh. 199", "Siehe, eine Jungfrau ist schwanger"},
		Comp{"Anh. 209", "Liebster Gott, vergißt Du mich"},
		Comp{"Anh. 210", "Wo sind meine Wunderwerke"},
		Comp{"Anh. 211", "Der Herr ist freundlich dem, der auf ihn harret"},
		Comp{"Anh. 212", "Vergnügende Flammen, verdoppelt die Macht"},
	},
	// Do we list Motets? (BWV 225-231)
	[]Comp{
		Comp{"232", "Hohe Messe"},
		Comp{"233", "Lutherische Messe in F-Dur"},
		Comp{"234", "Lutherische Messe in A-Dur"},
		Comp{"235", "Lutherische Messe in g-Moll"},
		Comp{"236", "Lutherische Messe in G-Dur"},
		Comp{"1081", "Credo in unum Deum"},
		Comp{"237", "Sanctus"},
		Comp{"238", "Sanctus"},
		Comp{"240", "Sanctus"},
		Comp{"241", "Sanctus"},
		Comp{"242", "Christe eleison"},
		Comp{"243", "Magnificat"},
		Comp{"243a", "Magnificat"},
		Comp{"1083", "Tilge, Höchster, meine Sünden"},
	},
	[]Comp{
		Comp{"244", "Matthäus-Passion"},
		Comp{"244b", "Matthäus-Passion (Frühfassung)"},
		Comp{"245", "Johannes-Passion"},
		Comp{"246", "Lukas-Passion*"},
		Comp{"247", "Markus-Passion"},
		Comp{"248", "Weihnachtsoratorium"},
		Comp{"248-1", "Jauchzet, frohlocket, auf, preiset die Tage"},
		Comp{"248-2", "Und es waren Hirten in derselben Gegend"},
		Comp{"248-3", "Herrscher des Himmels, erhöre das Lallen"},
		Comp{"248-4", "Fallt mit Danken, fallt mit Loben"},
		Comp{"248-5", "Ehre sei dir, Gott, gesungen"},
		Comp{"248-6", "Herr, wenn die stolzen Feinde schnauben"},
		Comp{"249", "Oster-Oratorium"},
		Comp{"249a", "Entfliehet, verschwindet, entweichet, ihr Sorgen"},
		Comp{"249b", "Verjaget, zerstreuet, zerrüttet, ihr Sterne"},
		// Comp{"11", "Lobet Gott in seinen Reichen"},
	},
	// Screw it, here are orchestral works
	[]Comp{
		Comp{"1041", "Concerto for violin and orchestra No. 1 - A minor"},
		Comp{"1042", "Concerto for violin and orchestra No. 2 - E major"},
		Comp{"1043", "Concerto for 2 violins and orchestra – Double Concerto - D minor"},
		Comp{"1044", "Concerto for flute, violin, harpsichord and orchestra – Triple Concerto - A minor"},
		Comp{"1045", "Cantata opening: 'Concerto' (Symphonic movement for violin and orchestra) - D major"},
		Comp{"1046", "Brandenburg Concerto No. 1 - F major"},
		Comp{"1046a", "Sinfonia (opening of BWV 208?) - F major"},
		Comp{"1047", "Brandenburg Concerto No. 2 - F major"},
		Comp{"1048", "Brandenburg Concerto No. 3 - G major"},
		Comp{"1049", "Brandenburg Concerto No. 4 - G major"},
		Comp{"1050", "Brandenburg Concerto No. 5 - D major"},
		Comp{"1050a", "Brandenburg Concerto No. 5a - D major"},
		Comp{"1051", "Brandenburg Concerto No. 6 - B♭ major"},
		Comp{"1052", "Concerto for harpsichord and orchestra No. 1 - D minor"},
		Comp{"1052a", "Concerto for harpsichord and orchestra No. 1a - D minor"},
		Comp{"1053", "Concerto for harpsichord and orchestra No. 2 - E major"},
		Comp{"1054", "Concerto for harpsichord and orchestra No. 3 - D major"},
		Comp{"1055", "Concerto for harpsichord and orchestra No. 4 - A major"},
		Comp{"1056", "Concerto for harpsichord and orchestra No. 5 - F minor"},
		Comp{"1057", "Concerto for harpsichord and orchestra No. 6 - F major"},
		Comp{"1058", "Concerto for harpsichord and orchestra No. 7 - G minor"},
		Comp{"1059", "Concerto for harpsichord and orchestra No. 8 (abandoned fragment of 1st movement) - D minor"},
		Comp{"1060", "Concerto for 2 harpsichords and orchestra No. 1 - C minor"},
		Comp{"1061", "Concerto for 2 harpsichords and orchestra No. 2 - C major"},
		Comp{"1061a", "Concerto for 2 harpsichords (No. 2) - C major"},
		Comp{"1062", "Concerto for 2 harpsichords and orchestra No. 3 - C minor"},
		Comp{"1063", "Concerto for 3 harpsichords and orchestra No. 1 - D minor"},
		Comp{"1064", "Concerto for 3 harpsichords and orchestra No. 2 - C major"},
		Comp{"1065", "Concerto for 4 harpsichords and orchestra - A minor"},
		Comp{"1066", "Orchestral Suite No. 1 - C major"},
		Comp{"1067", "Orchestral Suite No. 2 - B minor"},
		Comp{"1068", "Orchestral Suite No. 3 - D major"},
		Comp{"1069", "Orchestral Suite No. 4 - D major"},
		// Comp{"1071", ""},
		Comp{"1052R", "Concerto for violin - D minor"},
		Comp{"1055R", "Concerto for oboe - A major"},
		Comp{"1056R", "Concerto for violin - G minor"},
		Comp{"1060R", "Concerto for violin and oboe - C minor"},
		Comp{"1064R", "Concerto for three violins - D major"},
	},
}
